version: '2'
services:
  base:
    image: node:12.16.3-alpine3.9
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service/
    working_dir: /usr/src/service/
  install:
    extends:
      service: base
    command: npm i
volumes:
  nodemodules:
    external: true